import { configureFonts, MD3LightTheme, MD3Theme, MD3TypescaleKey } from "react-native-paper";
import { MD3Type } from "react-native-paper/lib/typescript/types";
import { theme } from "./theme";

const fontConfig: Partial<Record<MD3TypescaleKey, Partial<MD3Type>>> = {
  displayLarge: { fontFamily: 'Poppins_400Regular' },
  displayMedium: { fontFamily: 'Poppins_400Regular' },
  displaySmall: { fontFamily: 'Poppins_400Regular' },
  headlineLarge: {
    fontFamily: 'Poppins_500Medium',
    fontWeight: '500' as '500',
    letterSpacing: 0.25,
    lineHeight: 16,
    fontSize: 16,
  },
  headlineMedium: {
    fontFamily: 'Poppins_500Medium',
    fontWeight: '500' as '500',
    letterSpacing: 0.25,
    lineHeight: 16,
  },
  headlineSmall: {
    fontFamily: 'Poppins_500Medium',
    fontWeight: '500' as '500',
    letterSpacing: 0.25,
    lineHeight: 16,
    fontSize: 12,
  },
  titleLarge: {
    fontFamily: 'Poppins_500Medium',
    fontWeight: '500' as '500',
    letterSpacing: 0.25,
    lineHeight: 16,
    fontSize: 12,
  },
  titleMedium: {
    fontFamily: 'Poppins_500Medium',
    fontWeight: '500' as '500',
    letterSpacing: 0.25,
    lineHeight: 16,
    fontSize: 12,
  },
  titleSmall: {
    fontFamily: 'Poppins_500Medium',
    fontWeight: '500' as '500',
    letterSpacing: 0.25,
    lineHeight: 16,
    fontSize: 12,
  },
  labelLarge: { fontFamily: 'Poppins_500Medium' },
  labelMedium: {
    fontFamily: 'Poppins_500Medium',
    fontWeight: '500' as '500',
    letterSpacing: 0.25,
    lineHeight: 16,
    fontSize: 12,
  },
  labelSmall: { fontFamily: 'Poppins_400Regular' },
  bodyLarge: { fontFamily: 'Poppins_400Regular' },
  bodyMedium: { fontFamily: 'Poppins_400Regular' },
  bodySmall: { fontFamily: 'Poppins_400Regular' },
};

export const paperTheme: Partial<MD3Theme> = {
  ...MD3LightTheme,
  "colors": {
    "primary": theme.palette.primary,
    "onPrimary": theme.palette.background.default,
    "primaryContainer": "#CEE5FF",
    "onPrimaryContainer": "#001D32",
    "secondary": theme.palette.secondary,
    "onSecondary": theme.palette.background.default,
    "secondaryContainer": "#BCE9FF",
    "onSecondaryContainer": "#001F2A",
    "tertiary": "#006874",
    "onTertiary": theme.palette.background.default,
    "tertiaryContainer": "#97F0FF",
    "onTertiaryContainer": "#001F24",
    "error": theme.palette.error,
    "onError": theme.palette.background.default,
    "errorContainer": "#FFDADA",
    "onErrorContainer": "#410002",
    "background": "#FCFCFF",
    "onBackground": "#1A1C1E",
    "surface": "#FCFCFF",
    "onSurface": "#1A1C1E",
    "surfaceVariant": "#DEE3EB",
    "onSurfaceVariant": "#42474E",
    "outline": "#72777F",
    "outlineVariant": "#C2C7CF",
    "shadow": "#000000",
    "scrim": "#000000",
    "inverseSurface": "#2F3033",
    "inverseOnSurface": "#F0F0F4",
    "inversePrimary": "#96CCFF",
    "elevation": {
      "level0": "transparent",
      "level1": "#EFF4FA",
      "level2": "#E8F0F7",
      "level3": "#E0EBF4",
      "level4": "#DEEAF3",
      "level5": "#D9E7F1"
    },
    "surfaceDisabled": "rgba(26, 28, 30, 0.12)",
    "onSurfaceDisabled": "rgba(26, 28, 30, 0.38)",
    "backdrop": "rgba(44, 49, 55, 0.4)"
  },
  fonts: configureFonts({ config: fontConfig }),
}